### ISSUE TITLE
Request: Consider using a more compatible polya-gamma random sampler

### ISSUE THREAD

**Issue by zoj613** [pymc-devs/aesara#289]
## Description of your feature request

This is a feature request following a comment by @brandonwillard in https://github.com/pymc-devs/symbolic-pymc/pull/107 .

Looking at the source code, it appears that for random sampling, aesara uses a polya-gamma distribution random sampler whose API isn't quite compatible to scipy's. 
https://github.com/pymc-devs/aesara/blob/6c5a8fa044aae27a7ce2b6f90ef49f119bf5bdcd/aesara/tensor/random/basic.py#L387-L421

I would like to propose an alternative that has a scipy compatible API, which I think would ease the maintenance burden. `polyagamma` (repo: https://github.com/zoj613/polya-gamma) uses the same API as scipy/numpy statistical functions and is flexible and performant.

Here is an example usage:
```python
import numpy as np
from polyagamma import polyagamma

o = polyagamma()

# Get a 5 by 10 array of PG(1, 2) variates.
o = polyagamma(z=2, size=(5, 10))

# Pass sequences as input. Numpy's broadcasting rules apply here.
h = [[1, 2, 3, 4, 5], [9, 8, 7, 6, 5]]
o = polyagamma(h, 1)

# Pass an output array
out = np.empty(5)
polyagamma(out=out)
print(out)

# one can choose a sampling method from {devroye, alternate, gamma, saddle}.
# If not given, the default behaviour is a hybrid sampler that picks a method
# based on the parameter values.
o = polyagamma(method="saddle")

# We can also use an existing instance of `numpy.random.Generator` as a parameter.
# This is useful to reproduce samples generated via a given seed.
rng = np.random.default_rng(12345)
o = polyagamma(random_state=rng)
```

**Comment by brandonwillard** [comment]
Yes, using a library with a more NumPy-like interface would be much better; however, the Pólya-gamma distribution itself should actually be removed from this repository.  

`PolyaGammaRV` made it in from `symbolic-pymc` because some changes to `RandomVariable` were being made in this repository and I didn't want to leave it behind, so I moved and updated it as well.  Regardless, the `RandomVariable` implementations hosted by this repository are supposed to mirror NumPy's basic `numpy.random` offerings.  I don't think we can reasonably support _all_ types of distributions here.

Once we finalize the changes proposed in https://github.com/pymc-devs/pymc3/pull/4440, we can move the `PolyaGammaRV` to PyMC3 and consider using the new package there.

Besides that, one important consideration when switching packages is _stability_.  The `polyagamma` package doesn't appear to have CI set up, or report the package's testing and coverage status.  Those simple metrics would help justify the switch.

**Comment by zoj613** [comment]
> Yes, using a library with a more NumPy-like interface would be much better; however, the Pólya-gamma distribution itself should actually be removed from this repository.
> 
> `PolyaGammaRV` made it in from `symbolic-pymc` because some changes to `RandomVariable` were being made in this repository and I didn't want to leave it behind, so I moved and updated it as well. Regardless, the `RandomVariable` implementations hosted by this repository are supposed to mirror NumPy's basic `numpy.random` offerings. I don't think we can reasonably support _all_ types of distributions here.
> 
> Once we finalize the changes proposed in [pymc-devs/pymc3#4440](https://github.com/pymc-devs/pymc3/pull/4440), we can move the `PolyaGammaRV` to PyMC3 and consider using the new package there.
> 
> Besides that, one important consideration when switching packages is _stability_. The `polyagamma` package doesn't appear to have CI set up, or report the package's testing and coverage status. Those simple metrics would help justify the switch.

Thanks for the detailed response. I was not aware of these project plans. Nonetheless, I did update the project and added some basic CI and test coverage reporting.
