### ISSUE TITLE
JAX can't find GPU

### ISSUE THREAD

**Issue by JamesPHoughton** [pymc-devs/aesara#331]
## Description of your problem or feature request
Trying to run with a GPU on google colab, abandoned the approach described in [the docs](https://aesara.readthedocs.io/en/latest/tutorial/using_gpu.html) after seeing [this issue](
https://github.com/pymc-devs/aesara/issues/320) and switched to JAX.

However, running the [test script](https://aesara.readthedocs.io/en/latest/tutorial/using_gpu.html#testing-aesara-with-gpu) as test.py:

```
!AESARA_FLAGS='floatX=float32,mode="JAX"' python test.py
```
gives the error:
```
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Looping 1000 times took 0.431833 seconds
Result is [1.2317803 1.6187934 1.5227807 ... 2.2077181 2.2996776 1.6232328]
Used the cpu
```
(Unfortunately setting the TF flag doesn't seem to do anything, so I can't give more than that...)

Do I need to tell JAX more about  how to find the GPU? How?

**Reproducible example.**
You can run this colab notebook including all environment setups here:
https://colab.research.google.com/drive/18JIY-TEio7OiIMck9Wn14NkgTkY7oxif?usp=sharing

## Versions and main components
Everything is latest version as of today, miniconda, aesara, dependencies
- aesara: conda-forge/linux-64::aesara-2.0.2-py38h709712a_2

Aesara config (`python -c "import aesara; print(aesara.config)"`)
see the notebook: https://aesara.readthedocs.io/en/latest/tutorial/using_gpu.html#testing-aesara-with-gpu

**Comment by brandonwillard** [comment]
I don't see an error, just a JAX-specific warning about the GPU/TPU.  I recommend searching for solutions to that warning in [the JAX project's issues](https://github.com/google/jax/issues).  If those solutions are hindered by Aesara in any way, please create another issue with a minimal working example.

Otherwise, we can't really provide support for JAX itself; only things that relate to Aesara's JAX conversion capabilities directly.

**Comment by JamesPHoughton** [comment]
Thanks - one thing I was worried about was that I was asking Aesara to use JAX in the wrong way. From your comment, it sounds as if I'm doing things correctly vis-à-vis Aesera? That's helpful. I know the move to JAX is pretty recent, but it's been a bit hard to get started with, considering the directions the existing documentation sends one down. ;)

**Comment by brandonwillard** [comment]
Yeah, I don't see anything wrong with what you said you ran.  I get that warning all the time, because I don't have a GPU/TPU available on my local machine, so I know that's not necessarily a problem.

I just created #332 so that we can clarify some things related to GPU support, but that doesn't entirely address this situation, so I also made #333.
