### ISSUE TITLE
Import UnicodeDecodeError on windows

### ISSUE THREAD

**Issue by weidongzhou1994** [pymc-devs/aesara#337]
when I want to import pyms3, it encounters a problem：UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte

![image](https://user-images.githubusercontent.com/40510496/110569169-1ce4df80-818f-11eb-89c1-2382812bb21a.png)

**Comment by michaelosthege** [comment]
The fact that you put the `gbk` encoding in there (Chinese character sets) tells me that this is something about your setup.

If return values from `subprocess` calls to CLIs like the one of `gcc` are encoded in a Chinese character set I wouldn't be surprised if this is just the tip of the iceberg!
Instead of specifying `gbk` like you did above, I recommend that you find out where the `gbk` encoding came from in the first place.
